spring:
    application:
        name: TPM2ProvisionService
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER;MODE=LEGACY
        username: admin
        password: wokeadmin123
    sql:
        init:
            platform: h2
            mode: embedded
            schema-locations: classpath:/db/h2db-schema.sql
            continue-on-error: false
            separator: ;
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        # For debug only
        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
server:
    port: 8080
springdoc:
    # The raw OpenAPI descriptions (default path: /v3/api-docs)
    api-docs:
        path: /api-docs
    # With Swagger UI (default path: /swagger-ui)
    swagger-ui:
        path: /swagger-ui

logging:
    level:
        org.springframework.integration: DEBUG
        org.zeromq: DEBUG

zeromq:
    publisher:
        port: 6001
    subscriber:
        port: 6002